-- You need a player that can get hits. Who might be the most underrated? In 11.sql, write a SQL query to find the 10 least expensive players per hit in 2001.

-- Your query should return a table with three columns, one for the players’ first names, one of their last names, and one called “dollars per hit”.
-- You can calculate the “dollars per hit” column by dividing a player’s 2001 salary by the number of hits they made in 2001. Recall you can use AS to
-- rename a column.
-- Dividing a salary by 0 hits will result in a NULL value. Avoid the issue by filtering out players with 0 hits.
-- Sort the table by the “dollars per hit” column, least to most expensive. If two players have the same “dollars per hit”, order by first name,
-- followed by last name, in alphabetical order.
-- As in 10.sql, ensure that the salary’s year and the performance’s year match.
-- You may assume, for simplicity, that a player will only have one salary and one performance in 2001.


-- Clerk, my name’s Anneke. I live over at 900 Somerville Avenue. Not long ago, I sent out a special letter. It’s meant for
-- my friend Varsha. She’s starting a new chapter of her life at 2 Finnegan Street, uptown. (That address, let me tell you:
-- it was a bit tricky to get right the first time.) The letter is a
-- congratulatory note—a cheery little paper hug
-- from me to her, to celebrate this big move of hers. Can you check if it’s made its way to her yet?
-- 432 - Residential
-- --  +------+-----------------------+-----------------+---------------+
-- |  id  |       contents        | from_address_id | to_address_id |
-- +------+-----------------------+-----------------+---------------+
-- | 384  | Congratulatory letter | 432             | 854           |
-- | 2437 | String                | 432             | 484           |
-- | 3529 | Letter opener         | 432             | 585           |
-- | 5436 | Whiteboard            | 432             | 4984          |
-- +------+-----------------------+-----------------+---------------+
--  854 - Residential
-- +-----+-----------------------+-----------------+---------------+
-- | id  |       contents        | from_address_id | to_address_id |
-- +-----+-----------------------+-----------------+---------------+
-- | 384 | Congratulatory letter | 432             | 854           |
-- | 974 | Push pins             | 7376            | 854           |
-- +-----+-----------------------+-----------------+---------------+

-- Good day to you, deliverer of the mail. You might remember that not too long ago I made my way over from
-- the town of Fiftyville. I gave a certain box into your reliable hands and asked you to keep things low.
-- My associate has been expecting the package for a while now. And yet, it appears to have grown wings and
-- flown away. Ha! Any chance you could help clarify this mystery? Afraid there’s no “From” address.
-- It’s the kind of parcel that would add a bit more… quack to someone’s bath times, if you catch my drift.
-- +------+---------------+-----------------+---------------+
-- |  id  |   contents    | from_address_id | to_address_id |
-- +------+---------------+-----------------+---------------+
-- | 5098 | Duck debugger | NULL            | 50            |
-- +------+---------------+-----------------+---------------+
-- +-------+-----------+------------+------------+--------+----------------------------+
-- |  id   | driver_id | package_id | address_id | action |         timestamp          |
-- +-------+-----------+------------+------------+--------+----------------------------+
-- | 30123 | 10        | 5098       | 50         | Pick   | 2023-10-24 08:40:16.246648 |
-- | 30140 | 10        | 5098       | 348        | Drop   | 2023-10-24 10:08:55.610754 |
-- +-------+-----------+------------+------------+--------+----------------------------+
-- +-------+-----------+------------+------------+--------+----------------------------+
-- |  id   | driver_id | package_id | address_id | action |         timestamp          |
-- +-------+-----------+------------+------------+--------+----------------------------+
-- | 30123 | 10        | 5098       | 50         | Pick   | 2023-10-24 08:40:16.246648 |
-- | 30140 | 10        | 5098       | 348        | Drop   | 2023-10-24 10:08:55.610754 |
-- +-------+-----------+------------+------------+--------+----------------------------+
-- Oh, excuse me, Clerk. I had sent a mystery gift, you see, to my wonderful granddaughter,
-- off at 728 Maple Place. That was about two weeks ago. Now the delivery date has passed by
-- seven whole days and I hear she still waits, her hands empty and heart filled with anticipation.
-- I’m a bit worried wondering where my package has gone. I cannot for the life of me remember what’s
-- inside, but I do know it’s filled to the brim with my love for her.
-- Can we possibly track it down so it can fill her day with joy? I did send it from my home at 109 Tileston Street.
